import yaml
import os

# ---------------- CONFIG ----------------
yaml_file = "C:/Git/Hybrid/tools/buses/streamDef.yaml"
bus_yaml_file = "C:/Git/Hybrid/tools/buses/busDef.yaml"
arduino_sketch_dir = "C:/Git/Hybrid/tools/buses/main"
output_dir = os.path.join(arduino_sketch_dir, "src")
os.makedirs(output_dir, exist_ok=True)
# ---------------------------------------

# Load YAML
with open(yaml_file, "r") as f:
    streams = yaml.safe_load(f)
    
with open(bus_yaml_file, "r") as f:
    buses = yaml.safe_load(f)

streamSize = 8 #header, id, and timestamp
for stream_name, stream_info in streams.items():
    print(stream_name)
    
    includeBusesLines=""
    serializeBusesLines = ""
    copyArraysLines=""
    
    for index, busName in enumerate(stream_info['buses']): # look at each variable
        
        includeBusesLines += f'#include "{busName}.h"\n'

        
        for bus_name, bus_info in buses.items():
            if bus_name == busName:
                streamSize = streamSize + bus_info["size"]
                
        serializeBusesLines += f"    auto {busName}_serialized = {busName}.serialize();\n"

        if index == len(stream_info['buses'])-1: # if last bus, dont have the offset line
            copyArraysLines += f"    copy_array_into_buffer(buffer, offset, {busName}_serialized);\n"
        else: # include the offset if not the last bus
            copyArraysLines += f"    copy_array_into_buffer(buffer, offset, {busName}_serialized);\n    offset += {busName}_serialized.size();\n"
    
    streams[stream_name]['size'] = streamSize
    # -------- busPwr.h ---------------------------------------------------------------------------------------------------------
    header_path = os.path.join(output_dir, stream_name + ".h")

    h_template = """
//This was autogenerated by generateStreams.py

#ifndef {ifndef}
#define {ifndef}

#include <Arduino.h>
#include <array>
{includeBuses}
struct {streamName}Config {{
    int id;
    int size;
    int frequency;
    uint16_t header;
    
    std::array<uint8_t, {streamSize}> serialize(uint32_t currentMillis) const;
    
}};

template <size_t N, size_t M>
void copy_array_into_buffer(std::array<uint8_t, N>& buffer, size_t start_index,
                            const std::array<uint8_t, M>& data) {{
    for (size_t i = 0; i < M; ++i) {{
        if (start_index + i < N) {{
            buffer[start_index + i] = data[i];
        }}
    }}
}}

extern streamSerialTelemConfig streamSerialTelem;

#endif

"""

    output = h_template.format(
        streamName=stream_name,
        ifndef=stream_name.upper() + "_H",
        includeBuses=includeBusesLines,
        streamSize=streamSize,
    )
    
    with open(header_path, "w") as f:
        f.write(output)


    # -------- busPwr.cpp ---------------------------------------------------------------------------------------------------------
    cpp_path = os.path.join(output_dir, stream_name + ".cpp")
    
    cpp_template = """
//This was autogenerated by generateStreams.py

#include {streamdotH}
#include <string.h>
#include <Arduino.h>
#include "busPwr.h"
#include "busBME280.h"


{streamConfig} {streamName} = {{
    {id},
    {size},
    {freq},
    {header}
}};

std::array<uint8_t, {size}> streamSerialTelemConfig::serialize(uint32_t currentMillis) const {{
    std::array<uint8_t, {size}> buffer{{}}; // initialize all to 0

{serializeBuses}
    // Header
    buffer[0] = (streamSerialTelem.header >> 8) & 0xFF;
    buffer[1] = streamSerialTelem.header & 0xFF;

    // ID
    buffer[2] = (streamSerialTelem.id >> 8) & 0xFF;
    buffer[3] = streamSerialTelem.id & 0xFF;

    // Timestamp
    buffer[4] = (currentMillis >> 24) & 0xFF;
    buffer[5] = (currentMillis >> 16) & 0xFF;
    buffer[6] = (currentMillis >> 8)  & 0xFF;
    buffer[7] = currentMillis & 0xFF;
    
    // Copy serialized sub-arrays
    size_t offset = 8; 
{copyArrays}   
    return buffer;
}}

"""

    output = cpp_template.format(
        streamName=stream_name,
        streamdotH=f'"{stream_name}.h"',
        streamConfig=stream_name + "Config",
        id=stream_info['id'],
        size = streamSize,
        freq=stream_info['freq'],
        header=f"{stream_info['header']}",
        serializeBuses=serializeBusesLines,
        copyArrays=copyArraysLines,
    )
    
    with open(cpp_path, "w") as f:
        f.write(output)

    print(f"Generated files in Arduino sketch folder:\n- {header_path}\n- {cpp_path}")
    #print(f"{stream_name} length: {streamSize} bytes")


with open(yaml_file, "w") as f:
    yaml.safe_dump(streams, f, sort_keys=False)
    
        