import yaml
import os

# ---------------- CONFIG ----------------
yaml_file = "C:/Git/Hybrid/tools/buses/busDef.yaml"
arduino_sketch_dir = "C:/Git/Hybrid/tools/buses/main"
output_dir = os.path.join(arduino_sketch_dir, "src")
os.makedirs(output_dir, exist_ok=True)
# ---------------------------------------

type_map = {
    int: "int",
    float: "double",
    str: "char",
    bool: "bool"
}

# Load YAML
with open(yaml_file, "r") as f:
    buses = yaml.safe_load(f)
    
for bus_name, bus_info in buses.items():
    print(bus_name)

    # -------- busPwr.h ---------------------------------------------------------------------------------------------------------
    header_path = os.path.join(output_dir, bus_name + ".h")

    h_template = """
//This was autogenerated by generateBuses.py

#ifndef {ifndef}
#define {ifndef}
#include <Arduino.h>

struct {fieldConfig} {{
    int initVal;
    const char* unit;
    int startByte;
    int bytes;
    int bits;
    double c0;
    double c1;
    uint32_t pin;
}};

struct {busConfig} {{
    int id;
    int size;
    int frequency;
    const char* endian;
{fieldConfigLines} 
    const {fieldConfig}* getField(const char* fieldName) const;
    int bufferSize() const;
    void serialize(uint16_t* values, uint8_t* buffer) const;
}};

extern const {busConfig} {busName};

#endif

"""

    fieldConfigLines = ""
    for field_name, field_props in bus_info['data'].items():
        fieldConfigLines += f"    {bus_name + "FieldConfig"} {field_name};\n"
        
    output = h_template.format(
        busName=bus_name,
        ifndef=bus_name.upper() + "_H",
        fieldConfig=bus_name + "FieldConfig",
        busConfig=bus_name + "Config",
        fieldConfigLines=fieldConfigLines
    )
    
    with open(header_path, "w") as f:
        f.write(output)


    # -------- busPwr.cpp ---------------------------------------------------------------------------------------------------------
    cpp_path = os.path.join(output_dir, bus_name + ".cpp")
    
    cpp_template = """
//This was autogenerated by generateBuses.py

#include {busdotH}
#include <string.h>
#include <Arduino.h>

const {busConfig} {busName} = {{
    {id},
    {size},
    {freq},
    {endian},
{vals}
}};

const {fieldConfig}* {busConfig}::getField(const char* fieldName) const {{
{ifLines}
    return nullptr;
    
}}

void {busConfig}::serialize(uint16_t* values, uint8_t* buffer) const {{
    memset(buffer, 0, {busName}.size);
    
}}


"""
    valuesLines = ""
    ifLines = ""
    i=0
    for field_name, field_props in bus_info['data'].items(): # look at each variable
        i=i+1
        #valuesLines += f"    {field_props.values()},\n"
        thisLine = "{"
        for index, value in enumerate(field_props.values()): # get properties of each variable
            if index == len(field_props.values())-1:
                thisLine += f" {value}}}"
            elif index == 1:
                thisLine += f' "{value}",'
            else:
                thisLine += f" {value},"
        if i == len(bus_info['data'].items()):
            valuesLines += f"    {thisLine}"
        else:
            valuesLines += f"    {thisLine},\n"
    
        ifLines += f'   if (strcmp(fieldName, "{field_name}") == 0) return &{field_name};\n'
    

  
        
        
        
    output = cpp_template.format(
        busName=bus_name,
        busdotH=f'"{bus_name}.h"',
        fieldConfig=bus_name + "FieldConfig",
        busConfig=bus_name + "Config",
        id=bus_info['id'],
        size=bus_info['size'],
        freq=bus_info['freq'],
        endian=f'"{bus_info['endian']}"',
        vals=valuesLines,
        ifLines=ifLines
    )
    with open(cpp_path, "w") as f:
        f.write(output)

    print(f"Generated files in Arduino sketch folder:\n- {header_path}\n- {cpp_path}")
