#include "src/busPwr.h"
#include "src/busBME280.h"
#include "src/streamSerialTelem.h"
#include "src/SensorDataFrame.h"
#include <Arduino.h>
#include <HardwareSerial.h>
#include <Wire.h>
#include <Adafruit_Sensor.h>
#include <Adafruit_BME280.h>
#include <Adafruit_LSM9DS1.h>
#include <Adafruit_ADXL375.h>

/*======================================================================
Author: Tim Drake


// TO DO: 
- add SensorDataFrame.cpp to be autogenerated based on yaml initial values
- make settings config file for sensor attributes (ex. for setupLSM9DS1())
- add SD card features
*/



#define SDA_PIN PB11
#define SCL_PIN PB10

TwoWire Wire2(PB11, PB10); // SDA, SCL for I2C2
HardwareSerial MySerial(USART1);

Adafruit_BME280 bme;
Adafruit_LSM9DS1 lsm = Adafruit_LSM9DS1(&Wire2, 0x1E6B);
Adafruit_ADXL375 adx = Adafruit_ADXL375(12345, &Wire2);

unsigned long lastSendTime = 0;
unsigned long lastReadPwr = 0;
unsigned long lastReadBME = 0;
unsigned long lastReadLSM = 0;
unsigned long lastReadADXL = 0;

void sendSerialBuses(){
    // send data over various serial buses enabled in the config file
    // should be disabled for flight?

    // assume all are enabled for right now
    busPwr.sendPacket(thisFrame, MySerial);
    busBME280.sendPacket(thisFrame, MySerial);
    busLSM9DS1.sendPacket(thisFrame, MySerial);
    busADXL375.sendPacket(thisFrame, MySerial);
}

void setup() {
    MySerial.begin(1000000);
    Wire2.begin(PB11, PB10); // I2C2


    // Start sensors
    if(bme.begin(0x77, &Wire2)){
        bitSet(thisFrame.sensorsBIT, 0);
    }

    if(lsm.begin()) {
        bitSet(thisFrame.sensorsBIT, 1);
    }

    if(adx.begin(0x53)) {
        bitSet(thisFrame.sensorsBIT, 2);
    }   
}

void loop() {
    thisFrame.currentMillis = millis();

    //Gather data
    if (thisFrame.currentMillis - lastReadPwr >= 1000 / busPwr.frequency) {readPWR(thisFrame); lastReadPwr = thisFrame.currentMillis;}
    if (thisFrame.currentMillis - lastReadBME >= 1000 / busBME280.frequency) {readBME280(thisFrame);lastReadBME = thisFrame.currentMillis;}
    if (thisFrame.currentMillis - lastReadLSM >= 1000 / busLSM9DS1.frequency) {readLSM9DS1(thisFrame);lastReadLSM = thisFrame.currentMillis;}
    if (thisFrame.currentMillis - lastReadADXL >= 1000 / busADXL375.frequency) {readADXL375(thisFrame);lastReadADXL = thisFrame.currentMillis;}    
    
    // Send data over serial
    sendSerialBuses();
}
