#include "src/busPwr.h"
#include "src/busBME280.h"
#include "src/streamSerialTelem.h"
#include "src/SensorDataFrame.h"
#include "src/debug.h"
#include <Arduino.h>
#include <HardwareSerial.h>
#include <Wire.h>
#include <Adafruit_Sensor.h>
#include <Adafruit_BME280.h>

#include <SPI.h> 

/*======================================================================
Author: Tim Drake


// TO DO: 
- add ADXL375 SPI functionality
- add SensorDataFrame.cpp to be autogenerated based on yaml initial values
- make settings config file for sensor attributes (ex. for setupLSM9DS1())
- add SD card features
    - need to autogen sd frame and stuff.
- figure out SPI!!!!!!!!!!!
- add sensor debug bus
- have serial frame look at actual sensor value in separate function, rather than in the read function
- edit settings in gui
- figure out where to store the pin assignments
- eeprom
- restructure file system
- sensor calibration
- sensor settings gui
- add info at top of sd file (or separate file?)
- maybe flush sd less often, need to test how fast it can write
*/

const PinName BATTV_pin  = PA_0;
const PinName PIN_3V     = PA_1;
const PinName PIN_5V     = PA_8;

const PinName CS_AG_pin     = PA_2;
const PinName CS_MAG_pin    = PA_3;
const PinName CS_HIGHG_pin  = PA_4;

const PinName CS_SD_pin     = PB_12; // **do not use PA0–PA7 PB0–PB1 for SD CS


typedef struct{
    byte addr;
    float gainX;
    float gainY;
    float gainZ;
    int16_t rawX;
    int16_t rawY;
    int16_t rawZ;
    float x;
    float y;
    float z;
    uint32_t timeLastSamp = 0UL;
    uint32_t timeBtwnSamp = 10000UL;
    int datarate = 0;
    int range = 0;
    float lsb = 0;
    boolean newSamp = false;
    uint32_t clock = 1000000;     
    BitOrder bitOrder = MSBFIRST; 
    uint8_t dataMode;   
} sensor9DOFData;
sensor9DOFData accel;
sensor9DOFData gyro;
sensor9DOFData mag;
sensor9DOFData highG;

typedef struct{
    byte addr;
    float gain;
    int16_t raw;
    int16_t value;
    uint32_t timeLastSamp = 0UL;
    uint32_t timeBtwnSamp = 10000UL;
    int datarate = 0;
    int range = 0;
    boolean newSamp = false;
} sensorData;

sensorData temp;
sensorData pressure;
sensorData humidity;
sensorData baroAlt;

TwoWire Wire2(PB11, PB10); // SDA, SCL for I2C2
HardwareSerial MySerial(USART1);

Adafruit_BME280 bme;

unsigned long lastSendTime = 0;
unsigned long lastReadPwr = 0;
unsigned long lastReadBME = 0;
unsigned long lastReadLSM = 0;
unsigned long lastReadADXL = 0;

void sendSerialBuses(){
    if((thisFrame.currentMillis - streamSerialTelem.lastSendTime) >= 1000 / streamSerialTelem.frequency){
        streamSerialTelem.sendPacket(thisFrame, MySerial);
    };
}

void setup() {
    MySerial.begin(1000000);
    Wire2.begin(PB11, PB10); // I2C2

    // Start sensors
    beginLSM9DS1_AG();
    beginLSM9DS1_M();
    beginBME280();
    beginADXL375();

    // Start SD card
    beginSD();
}

void loop() {
    thisFrame.currentMillis = millis();

    // Read Data
    readPWR();
    readLSM9DS1_AG();
    readLSM9DS1_M();
    readBME280();
    readADXL375();
    
    sendSerialBuses();

    // Write to SD card
    writeSDFrame();
    




    thisFrame.loopTime = millis() - thisFrame.currentMillis;
}