#include "src/busPwr.h"
#include "src/busBME280.h"
#include "src/streamSerialTelem.h"
#include "src/SensorDataFrame.h"
#include <Arduino.h>
#include <HardwareSerial.h>
#include <Wire.h>
#include <Adafruit_Sensor.h>
#include <Adafruit_BME280.h>
#include <Adafruit_ADXL375.h>

#include <SPI.h> 

/*======================================================================
Author: Tim Drake


// TO DO: 
- add ADXL375 SPI functionality
- add SensorDataFrame.cpp to be autogenerated based on yaml initial values
- make settings config file for sensor attributes (ex. for setupLSM9DS1())
- add SD card features
- figure out SPI!!!!!!!!!!!
    - manually read the sensor?
    - no library
    - stuttery gui
- add sensor debug bus
- have serial frame look at actual sensor value in separate function, rather than in the read function
- have serial bus auto generated? everything on one bus, have deserialize also autogenerated
- edit settings in gui
*/

const PinName CS_AG_pin     = PA_2;
const PinName CS_MAG_pin    = PA_3;
const PinName CS_BARO_pin   = PA_4;

typedef struct{
  byte addr;
  float gainX;
  float gainY;
  float gainZ;
  int16_t rawX;
  int16_t rawY;
  int16_t rawZ;
  int16_t x;
  int16_t y;
  int16_t z;
  uint32_t timeLastSamp = 0UL;
  uint32_t timeBtwnSamp = 10000UL;
  int datarate = 0;
  int range = 0;
  boolean newSamp = false;
} sensor9DOFData;
sensor9DOFData accel;
sensor9DOFData gyro;
sensor9DOFData mag;

typedef struct{
  byte addr;
  float gain;
  int16_t raw;
  int16_t value;
  uint32_t timeLastSamp = 0UL;
  uint32_t timeBtwnSamp = 10000UL;
  int datarate = 0;
  int range = 0;
  boolean newSamp = false;
} sensorData;

sensorData temp;
sensorData pressure;
sensorData humidity;
sensorData baroAlt;

TwoWire Wire2(PB11, PB10); // SDA, SCL for I2C2
HardwareSerial MySerial(USART1);

Adafruit_BME280 bme;
//Adafruit_ADXL375 adx = Adafruit_ADXL375(12345, &Wire2);

unsigned long lastSendTime = 0;
unsigned long lastReadPwr = 0;
unsigned long lastReadBME = 0;
unsigned long lastReadLSM = 0;
unsigned long lastReadADXL = 0;

void sendSerialBuses(){
    // send data over various serial buses enabled in the config file
    // should be disabled for flight?

    // assume all are enabled for right now
    //if((thisFrame.currentMillis - busPwr.lastSendTime) >= 1000 / busPwr.frequency){
    //    busPwr.sendPacket(thisFrame, MySerial);
    //}

    //if((thisFrame.currentMillis - busBME280.lastSendTime) >= 1000 / busBME280.frequency){
    //    busBME280.sendPacket(thisFrame, MySerial);
    //}

    if((thisFrame.currentMillis - streamSerialTelem.lastSendTime) >= 1000 / streamSerialTelem.frequency){
        streamSerialTelem.sendPacket(thisFrame, MySerial);
    };
    
    //busADXL375.sendPacket(thisFrame, MySerial);
}

void setup() {
    MySerial.begin(1000000);
    Wire2.begin(PB11, PB10); // I2C2

    // Start sensors
    beginLSM9DS1_AG();
    beginLSM9DS1_M();

    beginBME280();

    //if(adx.begin(0x53)) {
    //    bitSet(thisFrame.sensorsBIT, 2);
    //}   
}

void loop() {
    thisFrame.currentMillis = millis();

    // Read Data
    readPWR();
    readLSM9DS1_AG();
    readLSM9DS1_M();
    readBME280();

    
    sendSerialBuses();
    
}