
//This was autogenerated by generateBuses.py

#include "busADXL375.h"
#include <string.h>
#include <Arduino.h>
#include "SensorDataFrame.h"

busADXL375Config busADXL375 = {
    6913,
    14,
    50,
    "little",
    "ADXL375",
    { 9999, "m/s^2", "float", 2, 4, 13, 0.0, 1.0, 0},
    { 9999, "m/s^2", "float", 6, 4, 13, 0.0, 1.0, 0},
    { 9999, "m/s^2", "float", 10, 4, 13, 0.0, 1.0, 0}
};

const busADXL375FieldConfig* busADXL375Config::getField(const char* fieldName) const {
   if (strcmp(fieldName, "highG_accelx") == 0) return &highG_accelx;
   if (strcmp(fieldName, "highG_accely") == 0) return &highG_accely;
   if (strcmp(fieldName, "highG_accelz") == 0) return &highG_accelz;

    return nullptr;
    
}

std::array<uint8_t, 14> busADXL375Config::serialize(SensorDataFrame &frame) const {
    std::array<uint8_t, 14> buffer{};
    buffer.fill(0);
    
    union {float f;uint32_t u;} highG_accelx_u;
    union {float f;uint32_t u;} highG_accely_u;
    union {float f;uint32_t u;} highG_accelz_u;
    
    highG_accelx_u.f = frame.highG_accelx;
    highG_accely_u.f = frame.highG_accely;
    highG_accelz_u.f = frame.highG_accelz;
    
    // ID
    buffer[0] = (6913 >> 8) & 0xFF;  // High byte (bits 9-8)
    buffer[1] = 6913 & 0xFF;         // Low byte (bits 7-0)
    
    //Data
    buffer[2] = (highG_accelx_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[3] = (highG_accelx_u.u >> 16) & 0xFF;
    buffer[4] = (highG_accelx_u.u >> 8)  & 0xFF;
    buffer[5] = highG_accelx_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[6] = (highG_accely_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[7] = (highG_accely_u.u >> 16) & 0xFF;
    buffer[8] = (highG_accely_u.u >> 8)  & 0xFF;
    buffer[9] = highG_accely_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[10] = (highG_accelz_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[11] = (highG_accelz_u.u >> 16) & 0xFF;
    buffer[12] = (highG_accelz_u.u >> 8)  & 0xFF;
    buffer[13] = highG_accelz_u.u & 0xFF;         // Least significant byte (LSB)

    
    
    return buffer;
}


