
//This was autogenerated by generateBuses.py

#include "busADXL375.h"
#include <string.h>
#include <Arduino.h>
#include <HardwareSerial.h>
#include "SensorDataFrame.h"

busADXL375Config busADXL375 = {
    6913,
    20,
    100,
    "little",
    "ADXL375",
    0,
    0,
    { 9999, "m/s^2", "float", 8, 4, 13, 0.0, 1.0, 0},
    { 9999, "m/s^2", "float", 12, 4, 13, 0.0, 1.0, 0},
    { 9999, "m/s^2", "float", 16, 4, 13, 0.0, 1.0, 0}
};

const busADXL375FieldConfig* busADXL375Config::getField(const char* fieldName) const {
   if (strcmp(fieldName, "highG_accelx") == 0) return &highG_accelx;
   if (strcmp(fieldName, "highG_accely") == 0) return &highG_accely;
   if (strcmp(fieldName, "highG_accelz") == 0) return &highG_accelz;

    return nullptr;
    
}

std::array<uint8_t, 20> busADXL375Config::serialize(SensorDataFrame &frame) const {
    std::array<uint8_t, 20> buffer{};
    buffer.fill(0);
    
    union {float f;uint32_t u;} highG_accelx_u;
    union {float f;uint32_t u;} highG_accely_u;
    union {float f;uint32_t u;} highG_accelz_u;
    
    highG_accelx_u.f = frame.highG_accelx;
    highG_accely_u.f = frame.highG_accely;
    highG_accelz_u.f = frame.highG_accelz;
    
    int i = 0;
    
    // ID
    buffer[i] = (6913 >> 8) & 0xFF; i++;
    buffer[i] = 6913 & 0xFF;        i++;   
    
    // Timestamp
    buffer[i] = (frame.currentMillis >> 24) & 0xFF; i++;
    buffer[i] = (frame.currentMillis >> 16) & 0xFF; i++;
    buffer[i] = (frame.currentMillis >> 8)  & 0xFF; i++;
    buffer[i] = frame.currentMillis & 0xFF;         i++;
    
    // Packets Sent
    buffer[i] = (busADXL375.packetsSent >> 8) & 0xFF; i++;
    buffer[i] = busADXL375.packetsSent & 0xFF;        i++;  
    
    //Data
    buffer[i] = (highG_accelx_u.u >> 24) & 0xFF; i++;
    buffer[i] = (highG_accelx_u.u >> 16) & 0xFF; i++;
    buffer[i] = (highG_accelx_u.u >> 8)  & 0xFF; i++;
    buffer[i] = highG_accelx_u.u & 0xFF;         i++;

    buffer[i] = (highG_accely_u.u >> 24) & 0xFF; i++;
    buffer[i] = (highG_accely_u.u >> 16) & 0xFF; i++;
    buffer[i] = (highG_accely_u.u >> 8)  & 0xFF; i++;
    buffer[i] = highG_accely_u.u & 0xFF;         i++;

    buffer[i] = (highG_accelz_u.u >> 24) & 0xFF; i++;
    buffer[i] = (highG_accelz_u.u >> 16) & 0xFF; i++;
    buffer[i] = (highG_accelz_u.u >> 8)  & 0xFF; i++;
    buffer[i] = highG_accelz_u.u & 0xFF;         i++;

    
    
    return buffer;
}

void busADXL375Config::sendPacket(SensorDataFrame &frame, HardwareSerial &serial) const {
    auto busADXL375_serialized = busADXL375.serialize(frame);

    serial.write(busADXL375_serialized.data(), busADXL375_serialized.size());
    
    busADXL375.packetsSent++;
    busADXL375.lastSendTime = frame.currentMillis;
}

