
//This was autogenerated by generateBuses.py

#ifndef BUSADXL375_H
#define BUSADXL375_H

#include <Arduino.h>
#include <Adafruit_BME280.h>
#include "SensorDataFrame.h"

struct busADXL375FieldConfig {
    int initVal;
    const char* unit;
    const char* type;
    int startByte;
    int bytes;
    int bits;
    double c0;
    double c1;
    uint32_t pin;
};

struct busADXL375Config {
    int id;
    int size;
    int frequency;
    const char* sensorName;
    const char* endian;
    uint16_t packetsSent;
    uint32_t lastSendTime;
    busADXL375FieldConfig highG_accelx;
    busADXL375FieldConfig highG_accely;
    busADXL375FieldConfig highG_accelz;
 
    const busADXL375FieldConfig* getField(const char* fieldName) const;
    std::array<uint8_t, 20> serialize(SensorDataFrame &frame) const;
    void sendPacket(SensorDataFrame &frame, HardwareSerial &serial) const;
};

extern busADXL375Config busADXL375;

#endif

