
//This was autogenerated by generateBuses.py

#ifndef BUSBME280_H
#define BUSBME280_H
#include <Arduino.h>

struct busBME280FieldConfig {
    int initVal;
    const char* unit;
    int startByte;
    int bytes;
    int bits;
    double c0;
    double c1;
    uint32_t pin;
};

struct busBME280Config {
    int id;
    int size;
    int frequency;
    const char* endian;
    busBME280FieldConfig temperatureC;
    busBME280FieldConfig pressurePasc;
    busBME280FieldConfig humidityRH;
 
    const busBME280FieldConfig* getField(const char* fieldName) const;
    int bufferSize() const;
    void serialize(uint16_t* values, uint8_t* buffer) const;
};

extern const busBME280Config busBME280;

#endif

