
//This was autogenerated by generateBuses.py

#include "busBME280.h"
#include <string.h>
#include <Arduino.h>

const busBME280Config busBME280 = {
    6911,
    20,
    50,
    "little",
    { 9999, "C", 0, 4, 32, 0.0, 1.0, 0},
    { 9999, "Pa", 4, 4, 32, 0.0, 1.0, 0},
    { 9999, "%", 8, 4, 32, 0.0, 1.0, 0}
};

const busBME280FieldConfig* busBME280Config::getField(const char* fieldName) const {
   if (strcmp(fieldName, "temperatureC") == 0) return &temperatureC;
   if (strcmp(fieldName, "pressurePasc") == 0) return &pressurePasc;
   if (strcmp(fieldName, "humidityRH") == 0) return &humidityRH;

    return nullptr;
    
}

void busBME280Config::serialize(uint16_t* values, uint8_t* buffer) const {
    memset(buffer, 0, busBME280.size);
    
}


