
//This was autogenerated by generateBuses.py

#include "busBME280.h"
#include <string.h>
#include <Arduino.h>
#include "SensorDataFrame.h"

busBME280Config busBME280 = {
    6911,
    18,
    50,
    "little",
    "BME280",
    { 9999, "C", "float", 6, 4, 32, 0.0, 1.0, 0},
    { 9999, "Pa", "float", 10, 4, 32, 0.0, 1.0, 0},
    { 9999, "%", "float", 14, 4, 32, 0.0, 1.0, 0},
    { 9999, "m", "float", 18, 4, 32, 0.0, 1.0, 0}
};

const busBME280FieldConfig* busBME280Config::getField(const char* fieldName) const {
   if (strcmp(fieldName, "temperatureC") == 0) return &temperatureC;
   if (strcmp(fieldName, "pressurePasc") == 0) return &pressurePasc;
   if (strcmp(fieldName, "humidityRH") == 0) return &humidityRH;
   if (strcmp(fieldName, "altitudeM") == 0) return &altitudeM;

    return nullptr;
    
}

std::array<uint8_t, 18> busBME280Config::serialize(SensorDataFrame &frame) const {
    std::array<uint8_t, 18> buffer{};
    buffer.fill(0);
    
    union {float f;uint32_t u;} temperatureC_u;
    union {float f;uint32_t u;} pressurePasc_u;
    union {float f;uint32_t u;} humidityRH_u;
    union {float f;uint32_t u;} altitudeM_u;
    
    temperatureC_u.f = frame.temperatureC;
    pressurePasc_u.f = frame.pressurePasc;
    humidityRH_u.f = frame.humidityRH;
    altitudeM_u.f = frame.altitudeM;
    
    // ID
    buffer[0] = (6911 >> 8) & 0xFF;  // High byte (bits 9-8)
    buffer[1] = 6911 & 0xFF;         // Low byte (bits 7-0)
    
    //Data
    buffer[2] = (temperatureC_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[3] = (temperatureC_u.u >> 16) & 0xFF;
    buffer[4] = (temperatureC_u.u >> 8)  & 0xFF;
    buffer[5] = temperatureC_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[6] = (pressurePasc_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[7] = (pressurePasc_u.u >> 16) & 0xFF;
    buffer[8] = (pressurePasc_u.u >> 8)  & 0xFF;
    buffer[9] = pressurePasc_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[10] = (humidityRH_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[11] = (humidityRH_u.u >> 16) & 0xFF;
    buffer[12] = (humidityRH_u.u >> 8)  & 0xFF;
    buffer[13] = humidityRH_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[14] = (altitudeM_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[15] = (altitudeM_u.u >> 16) & 0xFF;
    buffer[16] = (altitudeM_u.u >> 8)  & 0xFF;
    buffer[17] = altitudeM_u.u & 0xFF;         // Least significant byte (LSB)

    
    
    return buffer;
}


