
//This was autogenerated by generateBuses.py

#ifndef BUSBME280_H
#define BUSBME280_H

#include "sensorUtil.h"
#include <Arduino.h>
#include <Adafruit_BME280.h>
#include <Adafruit_LSM9DS1.h>

struct busBME280FieldConfig {
    int initVal;
    const char* unit;
    const char* type;
    int startByte;
    int bytes;
    int bits;
    double c0;
    double c1;
    uint32_t pin;
};

struct busBME280Config {
    int id;
    int size;
    int frequency;
    const char* sensorName;
    const char* endian;
    busBME280FieldConfig temperatureC;
    busBME280FieldConfig pressurePasc;
    busBME280FieldConfig humidityRH;
    busBME280FieldConfig altitudeM;
 
    float sensor_temperatureC; 
    float sensor_pressurePasc; 
    float sensor_humidityRH; 
    float sensor_altitudeM; 

    const busBME280FieldConfig* getField(const char* fieldName) const;
    std::array<uint8_t, 18> serialize() const;
};

extern busBME280Config busBME280;

#endif

