
//This was autogenerated by generateBuses.py

#include "busIMU.h"
#include <string.h>
#include <Arduino.h>
#include "sensorUtil.h"

busIMUConfig busIMU = {
    6912,
    38,
    50,
    "little",
    "LSM9DS1",
    { 65535, "m/s^2", "float", 0, 4, 32, 0.0, 1.0, 0},
    { 65535, "m/s^2", "float", 0, 4, 32, 0.0, 1.0, 0},
    { 65535, "m/s^2", "float", 0, 4, 32, 0.0, 1.0, 0},
    { 65535, "gauss", "float", 0, 4, 32, 0.0, 1.0, 0},
    { 65535, "gauss", "float", 0, 4, 32, 0.0, 1.0, 0},
    { 65535, "gauss", "float", 0, 4, 32, 0.0, 1.0, 0},
    { 65535, "dps", "float", 0, 4, 32, 0.0, 1.0, 0},
    { 65535, "dps", "float", 0, 4, 32, 0.0, 1.0, 0},
    { 65535, "dps", "float", 0, 4, 32, 0.0, 1.0, 0}
};

const busIMUFieldConfig* busIMUConfig::getField(const char* fieldName) const {
   if (strcmp(fieldName, "accelX") == 0) return &accelX;
   if (strcmp(fieldName, "accelY") == 0) return &accelY;
   if (strcmp(fieldName, "accelZ") == 0) return &accelZ;
   if (strcmp(fieldName, "magX") == 0) return &magX;
   if (strcmp(fieldName, "magY") == 0) return &magY;
   if (strcmp(fieldName, "magZ") == 0) return &magZ;
   if (strcmp(fieldName, "gyroX") == 0) return &gyroX;
   if (strcmp(fieldName, "gyroY") == 0) return &gyroY;
   if (strcmp(fieldName, "gyroZ") == 0) return &gyroZ;

    return nullptr;
    
}

std::array<uint8_t, 38> busIMUConfig::serialize() const {
    std::array<uint8_t, 38> buffer{};
    buffer.fill(0);
    
    union {float f;uint32_t u;} accelX_u;
    union {float f;uint32_t u;} accelY_u;
    union {float f;uint32_t u;} accelZ_u;
    union {float f;uint32_t u;} magX_u;
    union {float f;uint32_t u;} magY_u;
    union {float f;uint32_t u;} magZ_u;
    union {float f;uint32_t u;} gyroX_u;
    union {float f;uint32_t u;} gyroY_u;
    union {float f;uint32_t u;} gyroZ_u;
    
    accelX_u.f = imu_accel.acceleration.x;
    accelY_u.f = imu_accel.acceleration.y;
    accelZ_u.f = imu_accel.acceleration.z;
    magX_u.f = imu_mag.magnetic.x;
    magY_u.f = imu_mag.magnetic.y;
    magZ_u.f = imu_mag.magnetic.z;
    gyroX_u.f = imu_gyro.gyro.x;
    gyroY_u.f = imu_gyro.gyro.y;
    gyroZ_u.f = imu_gyro.gyro.z;
    
    // ID
    buffer[0] = (6912 >> 8) & 0xFF;  // High byte (bits 9-8)
    buffer[1] = 6912 & 0xFF;         // Low byte (bits 7-0)
    
    //Data
    buffer[2] = (accelX_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[3] = (accelX_u.u >> 16) & 0xFF;
    buffer[4] = (accelX_u.u >> 8)  & 0xFF;
    buffer[5] = accelX_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[6] = (accelY_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[7] = (accelY_u.u >> 16) & 0xFF;
    buffer[8] = (accelY_u.u >> 8)  & 0xFF;
    buffer[9] = accelY_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[10] = (accelZ_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[11] = (accelZ_u.u >> 16) & 0xFF;
    buffer[12] = (accelZ_u.u >> 8)  & 0xFF;
    buffer[13] = accelZ_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[14] = (magX_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[15] = (magX_u.u >> 16) & 0xFF;
    buffer[16] = (magX_u.u >> 8)  & 0xFF;
    buffer[17] = magX_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[18] = (magY_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[19] = (magY_u.u >> 16) & 0xFF;
    buffer[20] = (magY_u.u >> 8)  & 0xFF;
    buffer[21] = magY_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[22] = (magZ_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[23] = (magZ_u.u >> 16) & 0xFF;
    buffer[24] = (magZ_u.u >> 8)  & 0xFF;
    buffer[25] = magZ_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[26] = (gyroX_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[27] = (gyroX_u.u >> 16) & 0xFF;
    buffer[28] = (gyroX_u.u >> 8)  & 0xFF;
    buffer[29] = gyroX_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[30] = (gyroY_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[31] = (gyroY_u.u >> 16) & 0xFF;
    buffer[32] = (gyroY_u.u >> 8)  & 0xFF;
    buffer[33] = gyroY_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[34] = (gyroZ_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[35] = (gyroZ_u.u >> 16) & 0xFF;
    buffer[36] = (gyroZ_u.u >> 8)  & 0xFF;
    buffer[37] = gyroZ_u.u & 0xFF;         // Least significant byte (LSB)

    
    
    return buffer;
}


