
//This was autogenerated by generateBuses.py

#ifndef BUSIMU_H
#define BUSIMU_H

#include "sensorUtil.h"
#include <Arduino.h>
#include <Adafruit_BME280.h>
#include <Adafruit_LSM9DS1.h>

struct busIMUFieldConfig {
    int initVal;
    const char* unit;
    const char* type;
    int startByte;
    int bytes;
    int bits;
    double c0;
    double c1;
    uint32_t pin;
};

struct busIMUConfig {
    int id;
    int size;
    int frequency;
    const char* sensorName;
    const char* endian;
    busIMUFieldConfig accelX;
    busIMUFieldConfig accelY;
    busIMUFieldConfig accelZ;
    busIMUFieldConfig magX;
    busIMUFieldConfig magY;
    busIMUFieldConfig magZ;
    busIMUFieldConfig gyroX;
    busIMUFieldConfig gyroY;
    busIMUFieldConfig gyroZ;
 

    const busIMUFieldConfig* getField(const char* fieldName) const;
    std::array<uint8_t, 38> serialize() const;
};

extern busIMUConfig busIMU;

#endif

