
//This was autogenerated by generateBuses.py

#ifndef BUSLSM9DS1_H
#define BUSLSM9DS1_H

#include <Arduino.h>
#include <Adafruit_BME280.h>
#include "SensorDataFrame.h"

struct busLSM9DS1FieldConfig {
    int initVal;
    const char* unit;
    const char* type;
    int startByte;
    int bytes;
    int bits;
    double c0;
    double c1;
    uint32_t pin;
};

struct busLSM9DS1Config {
    int id;
    int size;
    int frequency;
    const char* sensorName;
    const char* endian;
    uint16_t packetsSent;
    uint32_t lastSendTime;
    busLSM9DS1FieldConfig accelx;
    busLSM9DS1FieldConfig accely;
    busLSM9DS1FieldConfig accelz;
    busLSM9DS1FieldConfig magx;
    busLSM9DS1FieldConfig magy;
    busLSM9DS1FieldConfig magz;
    busLSM9DS1FieldConfig gyrox;
    busLSM9DS1FieldConfig gyroy;
    busLSM9DS1FieldConfig gyroz;
 
    const busLSM9DS1FieldConfig* getField(const char* fieldName) const;
    std::array<uint8_t, 44> serialize(SensorDataFrame &frame) const;
    void sendPacket(SensorDataFrame &frame, HardwareSerial &serial) const;
};

extern busLSM9DS1Config busLSM9DS1;

#endif

