
//This was autogenerated by generateBuses.py

#include "busLSM9DS1.h"
#include <string.h>
#include <Arduino.h>
#include "SensorDataFrame.h"

busLSM9DS1Config busLSM9DS1 = {
    6912,
    38,
    50,
    "little",
    "LSM9DS1",
    { 9999, "m/s^2", "float", 2, 4, 32, 0.0, 1.0, 0},
    { 9999, "m/s^2", "float", 6, 4, 32, 0.0, 1.0, 0},
    { 9999, "m/s^2", "float", 10, 4, 32, 0.0, 1.0, 0},
    { 9999, "gauss", "float", 14, 4, 32, 0.0, 1.0, 0},
    { 9999, "gauss", "float", 18, 4, 32, 0.0, 1.0, 0},
    { 9999, "gauss", "float", 22, 4, 32, 0.0, 1.0, 0},
    { 9999, "dps", "float", 26, 4, 32, 0.0, 1.0, 0},
    { 9999, "dps", "float", 30, 4, 32, 0.0, 1.0, 0},
    { 9999, "dps", "float", 34, 4, 32, 0.0, 1.0, 0}
};

const busLSM9DS1FieldConfig* busLSM9DS1Config::getField(const char* fieldName) const {
   if (strcmp(fieldName, "accelx") == 0) return &accelx;
   if (strcmp(fieldName, "accely") == 0) return &accely;
   if (strcmp(fieldName, "accelz") == 0) return &accelz;
   if (strcmp(fieldName, "magx") == 0) return &magx;
   if (strcmp(fieldName, "magy") == 0) return &magy;
   if (strcmp(fieldName, "magz") == 0) return &magz;
   if (strcmp(fieldName, "gyrox") == 0) return &gyrox;
   if (strcmp(fieldName, "gyroy") == 0) return &gyroy;
   if (strcmp(fieldName, "gyroz") == 0) return &gyroz;

    return nullptr;
    
}

std::array<uint8_t, 38> busLSM9DS1Config::serialize(SensorDataFrame &frame) const {
    std::array<uint8_t, 38> buffer{};
    buffer.fill(0);
    
    union {float f;uint32_t u;} accelx_u;
    union {float f;uint32_t u;} accely_u;
    union {float f;uint32_t u;} accelz_u;
    union {float f;uint32_t u;} magx_u;
    union {float f;uint32_t u;} magy_u;
    union {float f;uint32_t u;} magz_u;
    union {float f;uint32_t u;} gyrox_u;
    union {float f;uint32_t u;} gyroy_u;
    union {float f;uint32_t u;} gyroz_u;
    
    accelx_u.f = frame.accelx;
    accely_u.f = frame.accely;
    accelz_u.f = frame.accelz;
    magx_u.f = frame.magx;
    magy_u.f = frame.magy;
    magz_u.f = frame.magz;
    gyrox_u.f = frame.gyrox;
    gyroy_u.f = frame.gyroy;
    gyroz_u.f = frame.gyroz;
    
    // ID
    buffer[0] = (6912 >> 8) & 0xFF;  // High byte (bits 9-8)
    buffer[1] = 6912 & 0xFF;         // Low byte (bits 7-0)
    
    //Data
    buffer[2] = (accelx_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[3] = (accelx_u.u >> 16) & 0xFF;
    buffer[4] = (accelx_u.u >> 8)  & 0xFF;
    buffer[5] = accelx_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[6] = (accely_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[7] = (accely_u.u >> 16) & 0xFF;
    buffer[8] = (accely_u.u >> 8)  & 0xFF;
    buffer[9] = accely_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[10] = (accelz_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[11] = (accelz_u.u >> 16) & 0xFF;
    buffer[12] = (accelz_u.u >> 8)  & 0xFF;
    buffer[13] = accelz_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[14] = (magx_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[15] = (magx_u.u >> 16) & 0xFF;
    buffer[16] = (magx_u.u >> 8)  & 0xFF;
    buffer[17] = magx_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[18] = (magy_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[19] = (magy_u.u >> 16) & 0xFF;
    buffer[20] = (magy_u.u >> 8)  & 0xFF;
    buffer[21] = magy_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[22] = (magz_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[23] = (magz_u.u >> 16) & 0xFF;
    buffer[24] = (magz_u.u >> 8)  & 0xFF;
    buffer[25] = magz_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[26] = (gyrox_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[27] = (gyrox_u.u >> 16) & 0xFF;
    buffer[28] = (gyrox_u.u >> 8)  & 0xFF;
    buffer[29] = gyrox_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[30] = (gyroy_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[31] = (gyroy_u.u >> 16) & 0xFF;
    buffer[32] = (gyroy_u.u >> 8)  & 0xFF;
    buffer[33] = gyroy_u.u & 0xFF;         // Least significant byte (LSB)

    buffer[34] = (gyroz_u.u >> 24) & 0xFF; // Most significant byte (MSB)
    buffer[35] = (gyroz_u.u >> 16) & 0xFF;
    buffer[36] = (gyroz_u.u >> 8)  & 0xFF;
    buffer[37] = gyroz_u.u & 0xFF;         // Least significant byte (LSB)

    
    
    return buffer;
}


