
//This was autogenerated by generateBuses.py

#include "busLSM9DS1.h"
#include <string.h>
#include <Arduino.h>
#include <HardwareSerial.h>
#include "SensorDataFrame.h"

busLSM9DS1Config busLSM9DS1 = {
    6912,
    56,
    100,
    "little",
    "LSM9DS1",
    0,
    0,
    { 9999, "m/s^2", "float", 8, 4, 32, 0.0, 1.0, 0},
    { 9999, "m/s^2", "float", 12, 4, 32, 0.0, 1.0, 0},
    { 9999, "m/s^2", "float", 16, 4, 32, 0.0, 1.0, 0},
    { 9999, "gauss", "float", 20, 4, 32, 0.0, 1.0, 0},
    { 9999, "gauss", "float", 24, 4, 32, 0.0, 1.0, 0},
    { 9999, "gauss", "float", 28, 4, 32, 0.0, 1.0, 0},
    { 9999, "dps", "float", 32, 4, 32, 0.0, 1.0, 0},
    { 9999, "dps", "float", 36, 4, 32, 0.0, 1.0, 0},
    { 9999, "dps", "float", 40, 4, 32, 0.0, 1.0, 0},
    { 9999, "deg", "float", 8, 4, 32, 0.0, 1.0, 0},
    { 9999, "deg", "float", 8, 4, 32, 0.0, 1.0, 0},
    { 9999, "deg", "float", 8, 4, 32, 0.0, 1.0, 0}
};

const busLSM9DS1FieldConfig* busLSM9DS1Config::getField(const char* fieldName) const {
   if (strcmp(fieldName, "accelx") == 0) return &accelx;
   if (strcmp(fieldName, "accely") == 0) return &accely;
   if (strcmp(fieldName, "accelz") == 0) return &accelz;
   if (strcmp(fieldName, "magx") == 0) return &magx;
   if (strcmp(fieldName, "magy") == 0) return &magy;
   if (strcmp(fieldName, "magz") == 0) return &magz;
   if (strcmp(fieldName, "gyrox") == 0) return &gyrox;
   if (strcmp(fieldName, "gyroy") == 0) return &gyroy;
   if (strcmp(fieldName, "gyroz") == 0) return &gyroz;
   if (strcmp(fieldName, "pitch") == 0) return &pitch;
   if (strcmp(fieldName, "roll") == 0) return &roll;
   if (strcmp(fieldName, "yaw") == 0) return &yaw;

    return nullptr;
    
}

std::array<uint8_t, 56> busLSM9DS1Config::serialize(SensorDataFrame &frame) const {
    std::array<uint8_t, 56> buffer{};
    buffer.fill(0);
    
    union {float f;uint32_t u;} accelx_u;
    union {float f;uint32_t u;} accely_u;
    union {float f;uint32_t u;} accelz_u;
    union {float f;uint32_t u;} magx_u;
    union {float f;uint32_t u;} magy_u;
    union {float f;uint32_t u;} magz_u;
    union {float f;uint32_t u;} gyrox_u;
    union {float f;uint32_t u;} gyroy_u;
    union {float f;uint32_t u;} gyroz_u;
    union {float f;uint32_t u;} pitch_u;
    union {float f;uint32_t u;} roll_u;
    union {float f;uint32_t u;} yaw_u;
    
    accelx_u.f = frame.accelx;
    accely_u.f = frame.accely;
    accelz_u.f = frame.accelz;
    magx_u.f = frame.magx;
    magy_u.f = frame.magy;
    magz_u.f = frame.magz;
    gyrox_u.f = frame.gyrox;
    gyroy_u.f = frame.gyroy;
    gyroz_u.f = frame.gyroz;
    pitch_u.f = frame.pitch;
    roll_u.f = frame.roll;
    yaw_u.f = frame.yaw;
    
    int i = 0;
    
    // ID
    buffer[i] = (6912 >> 8) & 0xFF; i++;
    buffer[i] = 6912 & 0xFF;        i++;   
    
    // Timestamp
    buffer[i] = (frame.currentMillis >> 24) & 0xFF; i++;
    buffer[i] = (frame.currentMillis >> 16) & 0xFF; i++;
    buffer[i] = (frame.currentMillis >> 8)  & 0xFF; i++;
    buffer[i] = frame.currentMillis & 0xFF;         i++;
    
    // Packets Sent
    buffer[i] = (busLSM9DS1.packetsSent >> 8) & 0xFF; i++;
    buffer[i] = busLSM9DS1.packetsSent & 0xFF;        i++;  
    
    //Data
    buffer[i] = (accelx_u.u >> 24) & 0xFF; i++;
    buffer[i] = (accelx_u.u >> 16) & 0xFF; i++;
    buffer[i] = (accelx_u.u >> 8)  & 0xFF; i++;
    buffer[i] = accelx_u.u & 0xFF;         i++;

    buffer[i] = (accely_u.u >> 24) & 0xFF; i++;
    buffer[i] = (accely_u.u >> 16) & 0xFF; i++;
    buffer[i] = (accely_u.u >> 8)  & 0xFF; i++;
    buffer[i] = accely_u.u & 0xFF;         i++;

    buffer[i] = (accelz_u.u >> 24) & 0xFF; i++;
    buffer[i] = (accelz_u.u >> 16) & 0xFF; i++;
    buffer[i] = (accelz_u.u >> 8)  & 0xFF; i++;
    buffer[i] = accelz_u.u & 0xFF;         i++;

    buffer[i] = (magx_u.u >> 24) & 0xFF; i++;
    buffer[i] = (magx_u.u >> 16) & 0xFF; i++;
    buffer[i] = (magx_u.u >> 8)  & 0xFF; i++;
    buffer[i] = magx_u.u & 0xFF;         i++;

    buffer[i] = (magy_u.u >> 24) & 0xFF; i++;
    buffer[i] = (magy_u.u >> 16) & 0xFF; i++;
    buffer[i] = (magy_u.u >> 8)  & 0xFF; i++;
    buffer[i] = magy_u.u & 0xFF;         i++;

    buffer[i] = (magz_u.u >> 24) & 0xFF; i++;
    buffer[i] = (magz_u.u >> 16) & 0xFF; i++;
    buffer[i] = (magz_u.u >> 8)  & 0xFF; i++;
    buffer[i] = magz_u.u & 0xFF;         i++;

    buffer[i] = (gyrox_u.u >> 24) & 0xFF; i++;
    buffer[i] = (gyrox_u.u >> 16) & 0xFF; i++;
    buffer[i] = (gyrox_u.u >> 8)  & 0xFF; i++;
    buffer[i] = gyrox_u.u & 0xFF;         i++;

    buffer[i] = (gyroy_u.u >> 24) & 0xFF; i++;
    buffer[i] = (gyroy_u.u >> 16) & 0xFF; i++;
    buffer[i] = (gyroy_u.u >> 8)  & 0xFF; i++;
    buffer[i] = gyroy_u.u & 0xFF;         i++;

    buffer[i] = (gyroz_u.u >> 24) & 0xFF; i++;
    buffer[i] = (gyroz_u.u >> 16) & 0xFF; i++;
    buffer[i] = (gyroz_u.u >> 8)  & 0xFF; i++;
    buffer[i] = gyroz_u.u & 0xFF;         i++;

    buffer[i] = (pitch_u.u >> 24) & 0xFF; i++;
    buffer[i] = (pitch_u.u >> 16) & 0xFF; i++;
    buffer[i] = (pitch_u.u >> 8)  & 0xFF; i++;
    buffer[i] = pitch_u.u & 0xFF;         i++;

    buffer[i] = (roll_u.u >> 24) & 0xFF; i++;
    buffer[i] = (roll_u.u >> 16) & 0xFF; i++;
    buffer[i] = (roll_u.u >> 8)  & 0xFF; i++;
    buffer[i] = roll_u.u & 0xFF;         i++;

    buffer[i] = (yaw_u.u >> 24) & 0xFF; i++;
    buffer[i] = (yaw_u.u >> 16) & 0xFF; i++;
    buffer[i] = (yaw_u.u >> 8)  & 0xFF; i++;
    buffer[i] = yaw_u.u & 0xFF;         i++;

    
    
    return buffer;
}

void busLSM9DS1Config::sendPacket(SensorDataFrame &frame, HardwareSerial &serial) const {
    auto busLSM9DS1_serialized = busLSM9DS1.serialize(frame);

    serial.write(busLSM9DS1_serialized.data(), busLSM9DS1_serialized.size());
    
    busLSM9DS1.packetsSent++;
    busLSM9DS1.lastSendTime = frame.currentMillis;
}

