
//This was autogenerated by generateBuses.py

#ifndef BUSPWR_H
#define BUSPWR_H
#include <Arduino.h>

struct busPwrFieldConfig {
    int initVal;
    const char* unit;
    int startByte;
    int bytes;
    int bits;
    double c0;
    double c1;
    uint32_t pin;
};

struct busPwrConfig {
    int id;
    int size;
    int frequency;
    const char* endian;
    busPwrFieldConfig battVolts;
    busPwrFieldConfig voltage3V;
    busPwrFieldConfig voltage5V;
 
    const busPwrFieldConfig* getField(const char* fieldName) const;
    int bufferSize() const;
    void serialize(uint16_t* values, uint8_t* buffer) const;
};

extern const busPwrConfig busPwr;

#endif

