
//This was autogenerated by generateBuses.py

#include "busPwr.h"
#include <string.h>
#include <Arduino.h>

busPwrConfig busPwr = {
    6910,
    8,
    50,
    "little",
    "PWR",
    { 1023, "V", "uint16_t", 0, 2, 10, 0.3009149658, 4.098150873, A0},
    { 1023, "V", "uint16_t", 2, 2, 10, 0.0, 1.0, A1},
    { 1023, "V", "uint16_t", 4, 2, 10, 0.0, 1.0, A2}
};

const busPwrFieldConfig* busPwrConfig::getField(const char* fieldName) const {
   if (strcmp(fieldName, "battVolts") == 0) return &battVolts;
   if (strcmp(fieldName, "voltage3V") == 0) return &voltage3V;
   if (strcmp(fieldName, "voltage5V") == 0) return &voltage5V;

    return nullptr;
    
}

void busPwrConfig::readSensor(){
    sensor_battVolts = (analogRead(busPwr.battVolts.pin) * busPwr.battVolts.c1) + busPwr.battVolts.c1;
    sensor_voltage3V = (analogRead(busPwr.voltage3V.pin) * busPwr.voltage3V.c1) + busPwr.voltage3V.c1;
    sensor_voltage5V = (analogRead(busPwr.voltage5V.pin) * busPwr.voltage5V.c1) + busPwr.voltage5V.c1;
}

std::array<uint8_t, 8> busPwrConfig::serialize() const {
    std::array<uint8_t, 8> buffer{};
    buffer.fill(0);
    
    
    
    // ID
    buffer[0] = (6910 >> 8) & 0xFF;  // High byte (bits 9-8)
    buffer[1] = 6910 & 0xFF;         // Low byte (bits 7-0)
    
    //Data
    buffer[2] = (sensor_battVolts >> 8) & 0xFF;  // High byte (bits 9-8)
    buffer[3] = sensor_battVolts & 0xFF;         // Low byte (bits 7-0)

    buffer[4] = (sensor_voltage3V >> 8) & 0xFF;  // High byte (bits 9-8)
    buffer[5] = sensor_voltage3V & 0xFF;         // Low byte (bits 7-0)

    buffer[6] = (sensor_voltage5V >> 8) & 0xFF;  // High byte (bits 9-8)
    buffer[7] = sensor_voltage5V & 0xFF;         // Low byte (bits 7-0)

    
    
    return buffer;
}


