
//This was autogenerated by generateBuses.py

#include "busPwr.h"
#include <string.h>
#include <Arduino.h>
#include "SensorDataFrame.h"

busPwrConfig busPwr = {
    6910,
    8,
    50,
    "little",
    "PWR",
    { 1023, "V", "uint16_t", 0, 2, 10, 0.3009149658, 4.098150873, A0},
    { 1023, "V", "uint16_t", 2, 2, 10, 0.0, 1.0, A1},
    { 1023, "V", "uint16_t", 4, 2, 10, 0.0, 1.0, A2}
};

const busPwrFieldConfig* busPwrConfig::getField(const char* fieldName) const {
   if (strcmp(fieldName, "battVolts") == 0) return &battVolts;
   if (strcmp(fieldName, "voltage3V") == 0) return &voltage3V;
   if (strcmp(fieldName, "voltage5V") == 0) return &voltage5V;

    return nullptr;
    
}

std::array<uint8_t, 8> busPwrConfig::serialize(SensorDataFrame &frame) const {
    std::array<uint8_t, 8> buffer{};
    buffer.fill(0);
    
    
    
    // ID
    buffer[0] = (6910 >> 8) & 0xFF;  // High byte (bits 9-8)
    buffer[1] = 6910 & 0xFF;         // Low byte (bits 7-0)
    
    //Data
    buffer[2] = (frame.battVolts >> 8) & 0xFF;  // High byte (bits 9-8)
    buffer[3] = frame.battVolts & 0xFF;         // Low byte (bits 7-0)

    buffer[4] = (frame.voltage3V >> 8) & 0xFF;  // High byte (bits 9-8)
    buffer[5] = frame.voltage3V & 0xFF;         // Low byte (bits 7-0)

    buffer[6] = (frame.voltage5V >> 8) & 0xFF;  // High byte (bits 9-8)
    buffer[7] = frame.voltage5V & 0xFF;         // Low byte (bits 7-0)

    
    
    return buffer;
}


