
//This was autogenerated by generateBuses.py

#ifndef BUSPWR_H
#define BUSPWR_H

#include "sensorUtil.h"
#include <Arduino.h>
#include <Adafruit_BME280.h>
#include <Adafruit_LSM9DS1.h>

struct busPwrFieldConfig {
    int initVal;
    const char* unit;
    const char* type;
    int startByte;
    int bytes;
    int bits;
    double c0;
    double c1;
    uint32_t pin;
};

struct busPwrConfig {
    int id;
    int size;
    int frequency;
    const char* sensorName;
    const char* endian;
    busPwrFieldConfig battVolts;
    busPwrFieldConfig voltage3V;
    busPwrFieldConfig voltage5V;
 
    uint16_t sensor_battVolts; 
    uint16_t sensor_voltage3V; 
    uint16_t sensor_voltage5V; 

    const busPwrFieldConfig* getField(const char* fieldName) const;
    std::array<uint8_t, 8> serialize() const;
};

extern busPwrConfig busPwr;

#endif

