
//This was autogenerated by generateBuses.py

#ifndef BUSPWR_H
#define BUSPWR_H

#include <Arduino.h>
#include <Adafruit_BME280.h>
#include "SensorDataFrame.h"

struct busPwrFieldConfig {
    int initVal;
    const char* unit;
    const char* type;
    int startByte;
    int bytes;
    int bits;
    double c0;
    double c1;
    uint32_t pin;
};

struct busPwrConfig {
    int id;
    int size;
    int frequency;
    const char* sensorName;
    const char* endian;
    uint16_t packetsSent;
    uint32_t lastSendTime;
    busPwrFieldConfig battVolts;
    busPwrFieldConfig voltage3V;
    busPwrFieldConfig voltage5V;
 
    const busPwrFieldConfig* getField(const char* fieldName) const;
    std::array<uint8_t, 14> serialize(SensorDataFrame &frame) const;
    void sendPacket(SensorDataFrame &frame, HardwareSerial &serial) const;
};

extern busPwrConfig busPwr;

#endif

