
//This was autogenerated by generateBuses.py

#ifndef DEBUG_H
#define DEBUG_H

#include <Arduino.h>
#include <Adafruit_BME280.h>
#include "SensorDataFrame.h"

struct debugFieldConfig {
    int initVal;
    const char* unit;
    const char* type;
    int startByte;
    int bytes;
    int bits;
    double c0;
    double c1;
    uint32_t pin;
};

struct debugConfig {
    int id;
    int size;
    int frequency;
    const char* sensorName;
    const char* endian;
    uint16_t packetsSent;
    uint32_t lastSendTime;
    debugFieldConfig loopTime;
 
    const debugFieldConfig* getField(const char* fieldName) const;
    std::array<uint8_t, 12> serialize(SensorDataFrame &frame) const;
    void sendPacket(SensorDataFrame &frame, HardwareSerial &serial) const;
};

extern debugConfig debug;

#endif

