
//This was autogenerated by generateBuses.py

#include "debug.h"
#include <string.h>
#include <Arduino.h>
#include <HardwareSerial.h>
#include "SensorDataFrame.h"

debugConfig debug = {
    6914,
    12,
    50,
    "little",
    "NA",
    0,
    0,
    { 0, "ms", "uint32_t", 8, 4, 32, 0.0, 1.0, 0}
};

const debugFieldConfig* debugConfig::getField(const char* fieldName) const {
   if (strcmp(fieldName, "loopTime") == 0) return &loopTime;

    return nullptr;
    
}

std::array<uint8_t, 12> debugConfig::serialize(SensorDataFrame &frame) const {
    std::array<uint8_t, 12> buffer{};
    buffer.fill(0);
    
    
    
    int i = 0;
    
    // ID
    buffer[i] = (6914 >> 8) & 0xFF; i++;
    buffer[i] = 6914 & 0xFF;        i++;   
    
    // Timestamp
    buffer[i] = (frame.currentMillis >> 24) & 0xFF; i++;
    buffer[i] = (frame.currentMillis >> 16) & 0xFF; i++;
    buffer[i] = (frame.currentMillis >> 8)  & 0xFF; i++;
    buffer[i] = frame.currentMillis & 0xFF;         i++;
    
    // Packets Sent
    buffer[i] = (debug.packetsSent >> 8) & 0xFF; i++;
    buffer[i] = debug.packetsSent & 0xFF;        i++;  
    
    //Data
    buffer[i] = (frame.loopTime >> 24) & 0xFF; i++;
    buffer[i] = (frame.loopTime >> 16) & 0xFF; i++;
    buffer[i] = (frame.loopTime >> 8)  & 0xFF; i++;
    buffer[i] = frame.loopTime & 0xFF;         i++;

    
    
    return buffer;
}

void debugConfig::sendPacket(SensorDataFrame &frame, HardwareSerial &serial) const {
    auto debug_serialized = debug.serialize(frame);

    serial.write(debug_serialized.data(), debug_serialized.size());
    
    debug.packetsSent++;
    debug.lastSendTime = frame.currentMillis;
}

