
//This was autogenerated by generateStreams.py

#include "streamSerialTelem.h"
#include <string.h>
#include <Arduino.h>
#include "busPwr.h"
#include "busBME280.h"


streamSerialTelemConfig streamSerialTelem = {
    6900,
    72,
    50,
    43962
};

std::array<uint8_t, 72> streamSerialTelemConfig::serialize(uint32_t currentMillis) const {
    std::array<uint8_t, 72> buffer{}; // initialize all to 0

    auto busPwr_serialized = busPwr.serialize();
    auto busBME280_serialized = busBME280.serialize();
    auto busIMU_serialized = busIMU.serialize();

    // Header
    buffer[0] = (streamSerialTelem.header >> 8) & 0xFF;
    buffer[1] = streamSerialTelem.header & 0xFF;

    // ID
    buffer[2] = (streamSerialTelem.id >> 8) & 0xFF;
    buffer[3] = streamSerialTelem.id & 0xFF;

    // Timestamp
    buffer[4] = (currentMillis >> 24) & 0xFF;
    buffer[5] = (currentMillis >> 16) & 0xFF;
    buffer[6] = (currentMillis >> 8)  & 0xFF;
    buffer[7] = currentMillis & 0xFF;
    
    // Copy serialized sub-arrays
    size_t offset = 8; 
    copy_array_into_buffer(buffer, offset, busPwr_serialized);
    offset += busPwr_serialized.size();
    copy_array_into_buffer(buffer, offset, busBME280_serialized);
    offset += busBME280_serialized.size();
    copy_array_into_buffer(buffer, offset, busIMU_serialized);
   
    return buffer;
}

