
//This was autogenerated by generateStreams.py

#ifndef STREAMSERIALTELEM_H
#define STREAMSERIALTELEM_H

#include <Arduino.h>
#include <array>
#include "SensorDataFrame.h"
#include "busPwr.h"
#include "busBME280.h"
#include "busLSM9DS1.h"
#include "busADXL375.h"

struct streamSerialTelemConfig {
    int id;
    int size;
    int frequency;
    uint16_t header;
    
    std::array<uint8_t, 87> serialize(SensorDataFrame &frame) const;
    
};

template <size_t N, size_t M>
void copy_array_into_buffer(std::array<uint8_t, N>& buffer, size_t start_index,
                            const std::array<uint8_t, M>& data) {
    for (size_t i = 0; i < M; ++i) {
        if (start_index + i < N) {
            buffer[start_index + i] = data[i];
        }
    }
}

extern streamSerialTelemConfig streamSerialTelem;

#endif

