
//This was autogenerated by generateStreams.py

#include "streamSerialTelem.h"
#include <string.h>
#include <Arduino.h>
#include "busPwr.h"
#include "busBME280.h"
#include "SensorDataFrame.h"


streamSerialTelemConfig streamSerialTelem = {
    6900,
    135,
    50,
    43962,
    0,
    0
};

std::array<uint8_t, 135> streamSerialTelemConfig::serialize(SensorDataFrame &frame) const {
    std::array<uint8_t, 135> buffer{}; // initialize all to 0

    auto busPwr_serialized = busPwr.serialize(frame);
    auto busBME280_serialized = busBME280.serialize(frame);
    auto busLSM9DS1_serialized = busLSM9DS1.serialize(frame);
    auto busADXL375_serialized = busADXL375.serialize(frame);
    auto debug_serialized = debug.serialize(frame);

    // Header
    buffer[0] = (streamSerialTelem.header >> 8) & 0xFF;
    buffer[1] = streamSerialTelem.header & 0xFF;

    // ID
    buffer[2] = (streamSerialTelem.id >> 8) & 0xFF;
    buffer[3] = streamSerialTelem.id & 0xFF;

    // Timestamp
    buffer[4] = (frame.currentMillis >> 24) & 0xFF;
    buffer[5] = (frame.currentMillis >> 16) & 0xFF;
    buffer[6] = (frame.currentMillis >> 8)  & 0xFF;
    buffer[7] = frame.currentMillis & 0xFF;
    
    // Sensor Built in Test
    buffer[8] = frame.sensorsBIT;
    
    // Copy serialized sub-arrays
    size_t offset = 9; 
    copy_array_into_buffer(buffer, offset, busPwr_serialized);
    offset += busPwr_serialized.size();
    copy_array_into_buffer(buffer, offset, busBME280_serialized);
    offset += busBME280_serialized.size();
    copy_array_into_buffer(buffer, offset, busLSM9DS1_serialized);
    offset += busLSM9DS1_serialized.size();
    copy_array_into_buffer(buffer, offset, busADXL375_serialized);
    offset += busADXL375_serialized.size();
    copy_array_into_buffer(buffer, offset, debug_serialized);
   
    return buffer;
}

void streamSerialTelemConfig::sendPacket(SensorDataFrame &frame, HardwareSerial &serial) const {
    auto streamSerialTelem_serialized = streamSerialTelem.serialize(frame);

    serial.write(streamSerialTelem_serialized.data(), streamSerialTelem_serialized.size());
    
    streamSerialTelem.packetsSent++;
    streamSerialTelem.lastSendTime = frame.currentMillis;
}

