
//This was autogenerated by generateStreams.py

#include "streamSerialTelem.h"
#include <string.h>
#include <Arduino.h>
#include "busPwr.h"
#include "busBME280.h"
#include "SensorDataFrame.h"


streamSerialTelemConfig streamSerialTelem = {
    6900,
    73,
    50,
    43962
};

std::array<uint8_t, 73> streamSerialTelemConfig::serialize(SensorDataFrame &frame) const {
    std::array<uint8_t, 73> buffer{}; // initialize all to 0

    auto busPwr_serialized = busPwr.serialize(frame);
    auto busBME280_serialized = busBME280.serialize(frame);
    auto busLSM9DS1_serialized = busLSM9DS1.serialize(frame);

    // Header
    buffer[0] = (streamSerialTelem.header >> 8) & 0xFF;
    buffer[1] = streamSerialTelem.header & 0xFF;

    // ID
    buffer[2] = (streamSerialTelem.id >> 8) & 0xFF;
    buffer[3] = streamSerialTelem.id & 0xFF;

    // Timestamp
    buffer[4] = (frame.currentMillis >> 24) & 0xFF;
    buffer[5] = (frame.currentMillis >> 16) & 0xFF;
    buffer[6] = (frame.currentMillis >> 8)  & 0xFF;
    buffer[7] = frame.currentMillis & 0xFF;
    
    // Sensor Built in Test
    buffer[8] = frame.sensorsBIT;
    
    // Copy serialized sub-arrays
    size_t offset = 9; 
    copy_array_into_buffer(buffer, offset, busPwr_serialized);
    offset += busPwr_serialized.size();
    copy_array_into_buffer(buffer, offset, busBME280_serialized);
    offset += busBME280_serialized.size();
    copy_array_into_buffer(buffer, offset, busLSM9DS1_serialized);
   
    return buffer;
}

